### ISSUE TITLE
Respect whitespace

### ISSUE THREAD

**Issue by mattfysh** [raptorjs/marko#10]
```
<my-first-tag>
<my-second-tag>
```
The new line between these two custom tags should be preserved.

**Comment by patrick-steele-idem** [comment]
Marking issue as closed since additional docs were added clarifying the whitespace rules for Marko. If there are still issues please let us know. Thanks.

**Comment by ivanslf** [comment]
Sorry to reopen an old issue, but how to set this option with marko/express?
