### ISSUE TITLE
render > output. result option

### ISSUE THREAD

**Issue by thomasJang** [raptorjs/marko#104]
i try 
```js
tmpl.render(data, function(err, output){
	if(!err)
		grunt.file.write(dest, output);
	else
		grunt.log.error(err);
});
```

output is
```html
<!DOCTYPE html> <html lang="en"><head><meta charset="UTF-8"><title></title></head><body><h1>My Page</h1>Hello World! <ul><li style="color: red">red</li><li style="color: green">green</li><li style="color: blue">blue</li></ul></body></html>
```

Is there a way, get output with `\n` 
plz help me

**Comment by thomasJang** [comment]
and i'm sorry i can't speak english

**Comment by patrick-steele-idem** [comment]
Hi @thomasJang, the marko compiler strips all whitespace by default (including trailing new lines). You can disable whitespace removal by doing the following:

```javascript
require('marko/compiler').defaultOptions.preserveWhitespace = true;
```

You'll need to force a recompile all your templates. The easiest way to do that is to set the `MARKO_CLEAN` environment to `true`:

```
MARKO_CLEAN=true node .
```

Of course, you can also just append the new line in your code:

```javascript
tmpl.render(data, function(err, output){
    if(!err)
        grunt.file.write(dest, output + '\n');
    else
        grunt.log.error(err);
});
```

Hopefully that answers your question, but if not please let me know.

**Comment by patrick-steele-idem** [comment]
Also, please check out the following docs: [Marko >> Whitespace](https://github.com/raptorjs/marko#whitespace)

**Comment by thomasJang** [comment]
thank you very much ~ marko perfect : )
