### ISSUE TITLE
marko-taglib.json change path

### ISSUE THREAD

**Issue by thomasJang** [raptorjs/marko#105]
I am creating `grunt marko plugin'
https://github.com/thomasJang/grunt-ax-marko

i have question. can i change marko-taglib.json path?
i know marko-taglib.json is same template path

**Comment by patrick-steele-idem** [comment]
Hi @thomasJang, can you please provide more clarity on what you are asking? The `marko-taglib.json` files are found relative to the template being compiled using the following search path: https://github.com/raptorjs/marko#taglib-discovery

If you can provide more details on what you are trying to accomplish I should then be able to provide better help. Thanks.

**Comment by thomasJang** [comment]
i'm sorry @patrick-steele-idem 

Questions were the location of a file whether the changes do predetermined position.

**Comment by thomasJang** [comment]
i'm sorry @patrick-steele-idem 
can be changed to another location, not the position determined the location of a file

**Comment by patrick-steele-idem** [comment]
Hi @thomasJang, the location cannot be changed because that would break other things (for example, the command-line compiler would not work). While we could make it possible to register additional `marko-taglib.json` files via code, I don't think that would be a good idea.

Not sure if it solves your use case but you can create a `marko-taglib.json` that imports other taglibs as shown below:

```json
{
    "taglib-imports": [
        "./path/to/another/marko-taglib.json"
    ],
    ...
}
``` 

Can you provide more details on your use case? Why do you need `marko-taglib.json` files to be in another location?

**Comment by thomasJang** [comment]
There is no big problem.It can be used now as.

However, if you want to place the resources and content, such as preferences for `java` project to another space may become a problem.
Also, in the case of the I, as follows, when you try to be able to set the location of each of the environment file it seems to be a problem.

https://www.npmjs.com/package/grunt-ax-marko#overview
```js
grunt.initConfig({
    ax_marko: {
        default: {
            options: {
                preserveWhitespace: true // expected output whitespace 
            },
            files: [
                {
                    src: "test/fixtures/*.html",
                    global_data: { // append data 
                        layout_path: "../layouts/basic.marko" // src relative path 
                    },
                    lang: {
                        ko: "test/lang/ko.json",
                        en: "test/lang/en.json"
                    },
                    dest: "test/expected",
                    output_extension: "html"
                }
            ]
        }
    },
});
```

Have met in such highly-level project is sincerely happy.
I is JSUI developers. Opportunity I want to make even UI in which the `marko` to base if.

**Comment by patrick-steele-idem** [comment]
Sounds good. If you run into any specific issues or get stuck please feel free to post a new issue. It's pretty easy to change things if necessary so just let us know. Thanks and good luck with your coding!
