### ISSUE TITLE
Programatically call taglibs

### ISSUE THREAD

**Issue by peterdotjs** [raptorjs/marko#14]
Is it possible to programmatically call taglibs?

Currently we can do the following when including template fragments:
```
<include template="src/modules/${module.alias}.marko"/>
```
I can include a different template based on the value of "module.alias".

I'd like to be able to have the same logic with taglibs. Something like this:

```
<var name="path" value="data.type" />
<app-test-${path} attr1="${data.attr1}" attr2="${data.attr2}" attr2="${data.attr2}"/>
```

Currently I can do the following:
```
<if test="data.type === "a">
    <app-test-a attr1="${data.attr1}" attr2="${data.attr2}" attr2="${data.attr2}"/>
</if>
<else-if test="data.type === "b">
    <app-test-b attr1="${data.attr1}" attr2="${data.attr2}" attr2="${data.attr2}"/>
</else-if>
<else>
    <app-test-c attr1="${data.attr1}" attr2="${data.attr2}" attr2="${data.attr2}"/>
</else>
```
This would work but I'd like to avoid having to copy over the same parameter code.

**Comment by patrick-steele-idem** [comment]
Custom tags are resolved to a "renderer" module at compile-time so it is not possible to support something like `<app-test-${path} ...>`. However, a custom tag is mapped directly to a renderer and you can invoke the renderer directly to have the HTML be written to the output stream. One option is to create a custom tag that delegates rendering to the appropriate renderer based some internal logic. Something like the following:

`src/components/app-test/renderer.js`:

```javascript
var rendererA = require('./variant-A/renderer');
var rendererB = require('./variant-B/renderer');
var rendererC = require('./variant-C/renderer');

module.exports = function render(input, out) {
    if (input.type === 'A') {
        rendererA(input, out);
    } else if (input.type === 'B') {
        rendererB(input, out);
    } else if (input.type === 'C') {
        rendererC(input, out);
    }
}
```

This nice thing about that approach is that to the outside world there is only a single tag, but internally the custom tag renderer can delegate to the appropriate implementation.

Let us know if that works or doesn't work for you.

**Comment by patrick-steele-idem** [comment]
ping. 

Can you please let me know if the proposed solution meets your needs so that I can close this issue or keep it open? Thanks.

**Comment by peterdotjs** [comment]
I'll try it out today and update you.
