### ISSUE TITLE
assign is missing in the documentation

### ISSUE THREAD

**Issue by pedramphp** [raptorjs/marko#19]
I was struggling with this issue for an hour until one of our coworkers told me how to do it.
Please add it to the documentation. ( to reassign a value to an existing variable we need to use assign)
```
<assign var="itemModel" value="items[itemIndex]" />
```

**Comment by patrick-steele-idem** [comment]
Yes, you are correct. Sorry for the missing docs. I don't mind adding the missing docs, but Pull Requests are always welcome.
