### ISSUE TITLE
Introduce `render-tag-if` instead of `body-only-if`

### ISSUE THREAD

**Issue by pedramphp** [raptorjs/marko#23]
Let's introduce a new tag attribute that will do the same thing as `body-only-if`.
Most of the time the intention is to skip the container and the focus is less in the body.

```html
<a href="${data.linkUrl}" body-only-if="!data.linkUrl">
    Some body content
</a>
```

Can get changed to:

```html
<a href="${data.linkUrl}" render-tag-if="data.linkUrl">
    Some body content
</a>
```

**Comment by patrick-steele-idem** [comment]
The meaning of `render-tag-if` is unclear since it could easily just be interpreted to be the same as `if`. That is, `render-tag-if` doesn't make it clear that only the body will render if the condition evaluates to `false`. `body-only-if` makes it clear that only the body content will be rendered (not the surrounding tag) if the condition evaluates to `true`.

Since `body-only-if` will rarely be used, I'm inclined to keep its usage as-is. What do you think?

**Comment by Estupendo** [comment]
I think you had a good point. The meaning of ```body-only-if``` is more clear than ```render-tag-if```, because, like you said, the condition is relative to the content in the tag, not to the tag itself.

**Comment by philidem** [comment]
I didn't know about `body-only-if` until I saw this issue, but after learning about it I would recommend keeping `body-only-if`. For me, the intention is to only render the body (and less about only rendering the tag). Kind of confusing but I think it works :)

**Comment by patrick-steele-idem** [comment]
@pedramphp, I agree with you that `body-only-if` feels a little backwards, but I am not seeing a better name. Thank you for the suggestion, but let's stick with `body-only-if` unless you have another idea on how this functionality could be provided in a less confusing way.

**Comment by redben** [comment]
Not really important but "body-only-if" confused me at first since it could be read as "render body, only if condition", instead of "render body only, if condition". May be changing to "only-body-if" could make it clearer...?

**Comment by yomed** [comment]
Good suggestion, `only-body-if` seems much clearer to me. I was also confused when I first used this feature.

**Comment by CestDiego** [comment]
I would add to this that maybe `only-body-when` or `only-body-if` make sense :)

**Comment by yomed** [comment]
Maybe the current wording comes off a bit strange because it intends to group the words "body only," but "only if" is already a phrase (as in "if and only if").
