### ISSUE TITLE
Inconsistent implementation of custom tags

### ISSUE THREAD

**Issue by pedramphp** [raptorjs/marko#26]
Any value under the `value` attribute are referenced to marko `objects` but the same is not true for custom tags.
```
<assign var="options" value = "util.getOptions(options, pattern)" />
```

Custom Tag only accepts `$DATA` 
```
<ebayui-refit-itemgrid-pattern viewModel = $grid options = $options />
```

The below code will through an error in marko
```
<ebayui-refit-itemgrid-pattern viewModel = "grid" options = "options" />
```

Marko should promote one way of passing variables to support consistency.

**Comment by patrick-steele-idem** [comment]
The HTML syntax does not allow attribute types to be distinguished (similar to JSON). This is unfortunate, but short of introducing a new language we must live with a separate schema that informs the compiler of the types of each attribute. Alternatively, we would assume that every attribute is a string and for `$`/`${ }` to change the type (more typing and ugly).

Therefore, in your example, you would just need to do the following:

```json
{
    "attributes": {
        "viewModel": "expression",
        "options": "expression"
    }
}
```

If we were willing to depart from an HTML parser, we could create our own HTML-like parser that supports the following:

```html
<my-component number=1/>
<my-component expression=(a + b)/>
<my-component string="hello"/>
<my-component boolean=true/>
```

If we were to go that route then we would lose syntax highlighting/completion/validation support from existing HTML editors and tools like [Emmet](http://emmet.io/).

**Comment by patrick-steele-idem** [comment]
Closing issue as I don't think there are any short-term actionable items. If you disagree please feel free to add comments.

**Comment by patrick-steele-idem** [comment]
Hey @pedramphp, please provide comments on the following proposal: https://github.com/raptorjs/marko/issues/90
