### ISSUE TITLE
IE conditionals support

### ISSUE THREAD

**Issue by vinodkl** [raptorjs/marko#27]
I am trying to target IE browsers with some simple IE conditionals, but it seem to fail in marko template.

My template has these simple conditionals, but its not getting targeted properly. I don’t see the classes being added. (works however in plain html)

&#x3C;!--[if lt IE 7]&#x3E; &#x3C;html class=&#x22;lt-ie9 lt-ie8 lt-ie7&#x22; lang=&#x22;${locale}&#x22;&#x3E; &#x3C;![endif]--&#x3E;
&#x3C;!--[if IE 7]&#x3E; &#x3C;html class=&#x22;lt-ie9 lt-ie8&#x22; lang=&#x22;${locale}&#x22;&#x3E; &#x3C;![endif]--&#x3E;
&#x3C;!--[if IE 8]&#x3E; &#x3C;html class=&#x22;lt-ie9&#x22; lang=&#x22;${locale}&#x22;&#x3E; &#x3C;![endif]--&#x3E;
&#x3C;!--[if !IE]&#x3E; --&#x3E;&#x3C;html lang=&#x22;${locale}&#x22;&#x3E;&#x3C;!--&#x3C;![endif]&#x2014;&#x3E;

anything to do with the HTML comment’s?

**Comment by patrick-steele-idem** [comment]
This is a known issue with a clean workaround. Marko ignores HTML comments and this breaks IE conditionals since the comments are never written to the output. I've suggested the following workaround in the past:

Create a custom tag named `<app-html>` that maps to the following renderer:

```javascript
module.exports = function render(input, out) {
    var lang = input.lang;
    
    out.write(
        '<!DOCTYPE html>' +
        '<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="' + lang + '"> <![endif]-->' +
        '<!--[if IE 7]> <html class="lt-ie9 lt-ie8" lang="' + lang + '"> <![endif]-->' +
        '<!--[if IE 8]> <html class="lt-ie9" lang="' + lang + '"> <![endif]-->' +
        '<!--[if !IE]> --><html lang="' + lang + '"><!--<![endif]—>');
        
    input.invokeBody();
    
    out.write('</html>');
};
```

Then in your page layout or page template:

```html
<app-html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Hello World</title>
        ...
    </head>
    <body>
        ...
    </body>
</app-html>
```

Output:

```html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en-us"> <![endif]-->
<!--[if IE 7]> <html class="lt-ie9 lt-ie8" lang="en-us"> <![endif]-->
<!--[if IE 8]> <html class="lt-ie9" lang="en-us"> <![endif]-->
<!--[if !IE]> --><html lang="en-us"><!--<![endif]—>
    <head>
        <meta charset="UTF-8">
        <title>Hello World</title>
        ...
    </head>
    <body>
        ...
    </body>
</html>
```

The benefit of this approach is that the HTML template is cleaner. In theory, we could look into a code change to introduce special handling for IE HTML comments. I'm open to ideas and/or Pull Requests, but hopefully the workaround solves your problem for now.

**Comment by patrick-steele-idem** [comment]
New version published with improvement: `marko@2.7.0`

**Comment by yomed** [comment]
Hey @patrick-steele-idem, not a big deal, but you may want to update your code sample above to use `renderBody(out)` instead of `invokeBody()`

**Comment by patrick-steele-idem** [comment]
Thanks for letting me know @yomed. IE conditional HTML comments are automatically preserved now so the workaround discussed is not needed.

**Comment by yomed** [comment]
I had noticed that even though they are preserved, variables weren't output correctly. I didn't dig into it too much, but I saw this issue and liked your `app-html` better anyway so I went with that.

So for example:
```
<!--[if IE 9]>
<html class="ie9" lang="$data.language"> <![endif]-->
<!--[if gt IE 9]><!-->
<html lang="$data.language">
<!--<![endif]-->
```

Would end up as:
```
<!--[if IE 9]>
<html class="ie9" lang="$data.language"> <![endif]-->
<!--[if gt IE 9]><!-->
<html lang="en">
<!--<![endif]-->
```

**Comment by patrick-steele-idem** [comment]
That's true, variables inside comments are not resolved. Does keep the template code cleaner as well. Thanks for sharing.
