### ISSUE TITLE
Support $global in template.renderSync

### ISSUE THREAD

**Issue by ianma** [raptorjs/marko#28]
This is not supported 

```javascript
template.renderSync({
  $global: {
    foo: "foo!"
   }
});
```

But this is (as seen in https://github.com/raptorjs/marko/issues/16)

```javascript
template.render{
  $global: {
    name: 'Frank'
  }
}, res);
```

The issue seems to be that `$global` processing is missing from the `renderSync` function.

https://github.com/raptorjs/marko/blob/master/runtime/marko-runtime.js#L65-L72
```javascript
Template.prototype = {
   renderSync: function(data) {
       var out = new AsyncWriter();
       out.sync();
       this._(data, out);
       out.end();
       return out.getOutput();
}
```

But can be found in the `render` function.

https://github.com/raptorjs/marko/blob/master/runtime/marko-runtime.js#L84-L126
```javascript
 render: function(data, out, callback) {
      ...
       var $global = data.$global;
       if ($global) {
           extend(out.global, $global);
       }
```

**Comment by patrick-steele-idem** [comment]
Fixed by #90f7dbf8c496d7c65d776042472fdbac646ef0d0
