### ISSUE TITLE
Proposal: deprecate invokeBody(...) in favor of renderBody(out)

### ISSUE THREAD

**Issue by patrick-steele-idem** [raptorjs/marko#36]
Currently, when using a custom tag that allows nested body content we compile the body content to a function that, when invoked, renders to the `out` from the closure. For example:

```javascript
exports.create = function(__helpers) {
  var __renderer = __helpers.r,
      button_tag = __renderer(require("../button-tag")),
      __tag = __helpers.t;

  return function render(data, out) {
    __tag(out,
      button_tag,
      {
          disabled: false
      },
      function() {
        out.write('My Button Label');
      });
  };
};
```

This allows `invokeBody()` to be invoked without any arguments. However, this is problematic for a few reasons:

- Rendering to a different `out` requires that the custom tag to be redeclared with an additional `out` variable that masks the `out` from the closure
- Outside the scope of Marko template, it is problematic for a UI component renderer to be invoked while supplying nested body content as part of the input if the the UI component renderer does not call the `input.invokeBody()` method with the desired `out`.

To solve these problems, we are planning on making the following change:

- Deprecating `input.invokeBody(...)` in favor of `input.renderBody(out)`
- When rendering the body content by invoking the `input.renderBody(out)` method, the `out` must always be provided as the first argument. For example:

```javascript
out.write('<button type="button">');
input.renderBody(out);
out.write('</button>');
```

The updated compiled template will be similar to the following:

```javascript
exports.create = function(__helpers) {
  var __renderer = __helpers.r,
      button_tag = __renderer(require("../button-tag")),
      __tag = __helpers.t;

  return function render(data, out) {
    __tag(out,
      button_tag,
      {
          disabled: false
      },
      function(out) {
        out.write('My Button Label');
      });
  };
};
```

Finally, a new `"body-function"` property will be offered that allows the body content of a custom tag to be converted to a custom property on the input. For example:

```json
{
    "body-function": "buildTabs(tabs)"
}
```

Sample compiled output:

```javascript
exports.create = function(__helpers) {
  var __renderer = __helpers.r,
      tabs_tag = __renderer(require("../tabs-tag")),
      __tag = __helpers.t;

  return function render(data, out) {
    __tag(out,
      tabs_tag,
      {
          title: "My Tabs",
          buildTabs: function(tabsHelper) {
            ...
          }
      });
  };
};
```

**Comment by philidem** [comment]
:+1:
