### ISSUE TITLE
Self-nested taglibs

### ISSUE THREAD

**Issue by dizlexik** [raptorjs/marko#41]
I started writing some code that I was really hoping would work but it doesn't seem to. I was wondering if self-nested taglibs would be possible because it would be extremely handy for my use case:
```json
{
  "tags": {
    "mytag": {
      "renderer": "./mytag",
      "attributes": {
        "data": "string"
      },
      "body-function": "getChildren(__children)",
      "import-var": {
        "children": "__children"
      }
    }
  }
}
```
```js
exports.render = function(input, out) {
  var children;
  if (input.getChildren) {
    children = [];
    input.getChildren({
      addChild: function(child) {
        children.push(child);
      }
    });
  }
  if (input.children)
    input.children.addChild(/* implementation detail */);
  else
    out.write(/* something utilizing children */);
};
```
```html
<mytag data="a">
  <mytag data="b" />
  <mytag data="c" />
</mytag>
```
So basically my question is whether or not it is somehow possible to include both "body-function" and "import-var" on the same tag and self-nest them. When I try this I get an error that __children is undefined. Is there a way to achieve this currently?

**Comment by dizlexik** [comment]
I actually solved my problem for now with a hack of using `"import-var": { "children": "arguments[1] }`, but obviously it would be much better if `children` existed in the compiled template and was null.

**Comment by patrick-steele-idem** [comment]
It is. I think you are running into a problem because you have an instance of `<mytag>` that is _not_ nested within another `<mytag>`. This is causing the scoped `__children` variable to be undefined and you are seeing an error. I suggest the following:

```json
"import-var": {
    "children": "typeof __children === 'undefined' ? null : __children"
}
```

That should avoid the '__children is undefined` error.

**Comment by dizlexik** [comment]
Ah yeah that makes sense. I've replaced my hack with that and it's working great now. Thanks so much!

**Comment by patrick-steele-idem** [comment]
Glad that worked for you and glad to see that you are taking advantage of these features!

Also, you might want to avoid a generic variable name such as `__children` and instead use `__mytag` or something that makes it clear where the variable came from and avoids possible variable collisions.

**Comment by dizlexik** [comment]
Ok cool, I'm still trying to figure out exactly how this all works. I have a little ways to go I think but so far so good. I started looking through the tests and have modified my taglib to use `"var": "children"` now and I've removed `body-function` in favor of using `renderBody(out, {...})` in my renderer. It's working perfectly now. Although I don't feel like I can be completely confident that I'm doing everything correctly because the documentation is a little lacking in this area at the moment, but I'm sure that'll change in the future.

FYI I'm building a simple taglib to render React components and it's actually working great. Maybe I'll publish it on npm if I get some time.

**Comment by patrick-steele-idem** [comment]
Sounds good. You are right that the documentation related to `body-function`, `renderBody(out)` and `import-var` could be improved. The plan is to eventually provide a separate Markdown document that goes into much more depth on building custom taglibs. There's actually a lot of really interesting things you can do at compile time using a custom transformer that manipulates the AST before the code generation phase. In the mean time, if you have any questions on how to accomplish something please ask here or on Gitter.

I would be curious to check out your wrapper around rendering a React component. I do feel like these two technologies do play nice together and welcome any solutions that can bridge the two.

Closing issue now that you have a working solution.
