### ISSUE TITLE
Component library support

### ISSUE THREAD

**Issue by viviangledhill** [raptorjs/marko#47]
Usecase:

We would like to add a library of components. The path would be:
/node_modules/component-library/node_modules/custom-component/lib/

If the rendered template is somewhere else then this path won't be discovered. 

Suggestion:

Add a way to add paths to the [discovery feature](https://github.com/raptorjs/marko#taglib-discovery)

**Comment by patrick-steele-idem** [comment]
How about the following?:

_component-library/marko-taglib.json__

```json
{
    "import-taglibs": ["./package.json"]
}
```

Behind the scenes, Marko would read the `package.json` file to find the `dependencies` object. It would then loop over all of the module dependencies and do the following:

```javascript
var taglibPathToTry = require.resolve('<module_name>/marko-taglib.json');

if (taglibPathToTry) {
    // Import the current taglib
}
```

Sound good?

**Comment by viviangledhill** [comment]
That would be great.

**Comment by patrick-steele-idem** [comment]
New versions published with enhancement:

`marko@1.6.7`
`marko@2.1.0`

Test for new feature are passing, but documentation has not been updated. Sample usage:
https://github.com/raptorjs/marko/blob/5a918e85d0a6e38e0aae4c96f5db273e48e1080b/test/test-project/marko-taglib.json#L102

Let me know if you see any issues.
