### ISSUE TITLE
Template compiler automatically closing html tags (breaking layout)

### ISSUE THREAD

**Issue by patbegg** [raptorjs/marko#56]
Hi,
I have a problem with components having their HTML tags closed, incorrectly, by the compiler. For example if I have the following components and html content (shown simplified):
<app-header> (components/app-header/template.marko)
HTML content: `<div class="wrapper"><div class="content">`

<app-footer> (components/app-footer/template.marko)
HTML content: `</div></div>`

index.js
HTML content: `<app-header></app-header><div>content here</div><app-footer></app-footer>`

I can see the problem. The `<app-header>` component's compiled .js file has added the closing 'div' tags automatically, which breaks the layout as the 'wrapper' and 'content' elements are now closed, when they should be left open to contain the main page content.

Is there any setting to prevent this or a different way of laying out the pages?

Thanks,
Pat

**Comment by patrick-steele-idem** [comment]
Hi @patbegg. We use an HTML parser that follows the same HTML parser rules as a web browser so each templates should be valid HTML documents which means you can't break out the opening and closing tags for an element into separate templates. However, that is not really a problem in practice and the recommended solution is to use the [layout taglib](https://github.com/raptorjs/marko#layout-taglib) to define the skeleton of your page. For your example, you would want to do something like the following:

___src/pages/home/template.marko:___

```html
<layout-use template="../layouts/default/template.marko">
    <layout-put into="title">My Page Title</layout-put>
    <layout-put into="body">content here</layout-put>
</layout-use>
```

___src/layouts/default/template.marko:___

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><layout-placeholder name="title"/></title>
</head>
<body>
    <app-header/>
    <div>
        <layout-placeholder name="body"/>
    </div>
    <app-footer/>
</body>
</html>
```

Let me know if that does or does not solve your problem.

**Comment by patbegg** [comment]
Ok, that makes sense. Once again thanks for the quick response and easy to understand explanation - it really makes a difference.
Thanks,
Pat

**Comment by patrick-steele-idem** [comment]
You're welcome. I hope that solution worked out for you.
