### ISSUE TITLE
Simplify how parent/child relationships are handled for custom tags.

### ISSUE THREAD

**Issue by patrick-steele-idem** [raptorjs/marko#61]
Currently, to set up a parent/child relationship between custom tags requires a decent amount of code.

Here's an idea how it can be improved:

Let's say we want to achieve the following:

```html
<app-tabs orientation="vertical">
    <app-tab label="Tab 1">
        Content for Tab 1
    </app-tab>
    <app-tab label="Tab 2">
        Content for Tab 2
    </app-tab>
</app-tabs>
```

This could be described in a single `app-tabs/marko-taglib.json` as shown below:

```json
{
    "attributes": {
        "orientation": "string"
    },
    "nested-tags": {
        "app-tab": {
            "target-property": "tabs",
            "repeated": true,
            "attributes": {
                "label": "string"
            }
        }
    }
}
```

In the renderer, the nested tabs could be accessed using the `input.tabs` property that will be an array:

```javascript
exports.renderer = function(input, out) {
    var tabs = input.tabs;
    tabs.forEach(function(tab) {
        // ...
    });
};
```

Another example:

```html
<app-overlay visible="false">
    <app-overlay-header>
        This is the header content
    </app-overlay-header>
    <app-overlay-body>
        This is the body content
    </app-overlay-body>
    <app-overlay-footer>
        This is the footer content
    </app-overlay-footer>
</app-overlay>
```

This could be described in a single `app-overlay/marko-taglib.json` as shown below:

```json
{
    "attributes": {
        "visible": "boolean"
    },
    "nested-tags": {
        "app-overlay-header": {
            "target-property": "header",
            "repeated": false
        },
        "app-overlay-body": {
            "target-property": "body",
            "repeated": false
        },
        "app-overlay-footer": {
            "target-property": "footer",
            "repeated": false
        }
    }
}
```

In the renderer, the nested header, body and footer content could be accessed as shown below:

```javascript
exports.renderer = function(input, out) {
    var header = input.header;
    var body = input.body;
    var footer = input.footer;
    
    console.log(typeof header.renderBody); // Output: 'function'
    console.log(typeof body.renderBody); // Output: 'function'
    console.log(typeof footer.renderBody); // Output: 'function'
};
```

**Comment by philidem** [comment]
I like this concept a lot. It might be helpful to include a snippet of what the compiled output might look like so that we can discuss.

Here are some alternate property names for configuring the nested tag:
- **target-property:** property (a little shorter)
- **repeated:** limit (a numeric value), repeatable

Alternatively have just "target-property" and use `[]` to denote allowed repeatability:
- Allow any number of tabs: `target-property: "tabs[]"`
- Allow one tab: `target-property: "tabs[1]"`
- Allow two tabs: `target-property: "tabs[2]"`
- Allow only a single tab: `target-property: "tab"`

Also, perhaps the target property should always be an array and don't require the compiler to check constraints about repeatability of nested tag.

Something even crazier to avoid some of the JSON clunkiness:
```json
{
    "attributes": {
        "visible": "boolean"
    },
    "nested-tags": [
        "app-overlay-title => title",
        "app-overlay-header => header[]",
        "app-overlay-body => body[1]",
        "app-overlay-footer => footer[]"
    ]
}
```

**Comment by patrick-steele-idem** [comment]
I like the idea of dropping the `repeated`/`repeatable` property and, instead, just use the `[]` suffix to denote something that should repeatable. However, I don't think we should allow `[<max_count>]`.

I think I prefer `target-property` since it I think it is a little more clear that this is the name of the target property.

I don't think we need the short-hand because it prevents attributes from being defined for the nested tags, but I might be able to be persuaded.

**Comment by philidem** [comment]
I am worried that repeatable will be the most common case and that people will forget to add the `[]` to the target property name. That's why I was wondering if we should always assume arrays...

I like the shorthand notation for the most common case. We can implement the longhand approach first and then see if shorthand makes sense.

**Comment by patrick-steele-idem** [comment]
Definitely don't want to have nested tags always produce an array. I think that will make the tag renderer more complicated than it needs to be.

**Comment by philidem** [comment]
@patrick-steele-idem and I discussed this and the proposal looks more like this:
```json
{
    "attributes": {
        "orientation": "string"
    },
    "taglib": {
        "tags": {
            "app-tab": {
                "target-property": "tabs[]",
                "attributes": {
                    "label": "string"
                }
            }
        }
    }
}
```

Basically, you can now declare taglibs within other tags. If the **target-property** exists for a tag then this creates the parent/child relationship between the parent tag and the child tag. When taglibs are declared within another tag, then that taglib is associated with a parent taglib.

**Comment by patrick-steele-idem** [comment]
Thanks for summarizing @philidem. I'm going to start the implementation now.

**Comment by schetnikovich** [comment]
This proposal looks really nice! Just trying to understand how flexible it is. First thing that come to my mind is about more than one level of hierarchy. How can be the following tag described in `marko-taglib.json`:

```html
<sidebar-navigation>
    <sidebar-navigation-section title="Software">
        <sidebar-navigation-item href="/linux" title="linux"/>
        <sidebar-navigation-item href="/windows" title="Windows"/>
    </sidebar-navigation-section>
    <sidebar-navigation-section title="Devices">
        <sidebar-navigation-item href="/ipad" title="iPad"/>
        <sidebar-navigation-item href="/xbox" title="Xbox"/>
    </sidebar-navigation-section>
</sidebar-navigation>
```

And there are use-cases for unlimited hierarchy (though very uncommon):

```html
<menu-widget>
    <menu-item title="Help">
        <menu-item title="About" />
        <menu-item title="FAQ" />
    </menu-item>
    <menu-item title="File">
        <menu-item title="Save" />
        <menu-item title="Open with">
            <menu-item title="Sublime" />
            <menu-item title="VIM" />
        </menu-item>
    </menu-item>
    <menu-item title="View" />
</menu-widget>
```

Will it be possible to describe such nesting? If we'll go with the proposed way, we need to define taglib inside taglib inside taglib :) 

Here is an example for the `sidebar-navigation` shown above:

```js
{
    "attributes": {
        "orientation": "string"
    },
    "taglib": {
        "tags": {
            "sidebar-navigation-section": {
                "target-property": "sections[]",
                "attributes": {
                    "title": "string"
                },
                "taglib": {
                    "tags": {
                        "sidebar-navigation-item": {
                            "target-property": "items[]",
                            "attributes": {
                                "href": "string",
                                "title": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}
```
