### ISSUE TITLE
Making $global vars available for all components and templates

### ISSUE THREAD

**Issue by patbegg** [raptorjs/marko#63]
Hi,
Is there a way to make a variable available to all layouts templates without having to pass it in every template.render()?
For example, i'm using <layout> and have a <app-nav> component in that layout. I want to be able to render/not render certain navigation elements depending on whether the suer is logged in or not. At present I have to pass a variable in every controller like this:
`$global: { env: locals.env, user: locals.user }`
but I have to do that in every controller ( where I call template.render() ) e.g. login, signup etc etc. Is there any way to make variable available to all templates/components rather than sending the data each time in template.render()?

Thanks,
Pat

**Comment by patrick-steele-idem** [comment]
Sorry for the delayed response, but better late than never...

You have a few options:

___Option 1) Access req/res properties using `out.stream`___

Assuming you render the top-level page template directly to an HTTP response stream using `template.render(viewModel, res)`, you can access the HTTP request and response objects by doing the following:

```javascript
exports.renderer = function(input, out) {
    var res = out.stream;
    var req = res.req; // The "req" property is added to the "res" object by Express
}
```

___Option 2) Use continuation local storage (CLS)___

You could use something like [continuation-local-storage](https://github.com/othiym23/node-continuation-local-storage) (or [request-local](https://www.npmjs.com/package/request-local) which is a small wrapper on top of CLS) to make request-specific information automatically available to all templates and modules, but I've found that CLS can be very problematic. I think you are better off passing in the request-specific globals via the `$global` property or going with Option 1. 

-----

I hope that helps. Please feel free to reopen this issue if you would like to discuss some more.
