### ISSUE TITLE
Alternative proposal for parent/child relationships

### ISSUE THREAD

**Issue by schetnikovich** [raptorjs/marko#64]
Proposal #61 suggests some solution to simplify "parent/child relationships". I'm trying to understand how conceptually we are selling this solution to the end user. We are telling that user should "connect" parent and child tags, but maybe user does not need child tags? Maybe he just needs a way to express complex `input` object using declarative markup.

If we step back and overview tags again, we can say that tag is a function with the following signature:

```js
var customTag = function(input, out) {
    // ...
};
```

Instead of calling it directly in the code, we found a way to "call" it declaratively with the following markup:

```html
<custom-tag title="Hello" href="/some/url" />
```

Naive equivalent of the above declarative "call" is the following function call:

```js
customTag({ title: "Hello", href: "/some/url", renderBody: function() {} });
```

It means that declarative `<custom-tag />` is used to define the shape of the `input` object for `customTag` function. Nothing new here, this is just an introduction.

But you can notice, that declaratively you can define only first-level properties or functions of the `input` object. 

### Alternative definition of the problem

In proposal #61 idea was to simplify parent/child relationship. But maybe we can solve the same problem if declarative "call" would support definition of complex `input` objects. Actually, the notion of the `target-property` suggests us that we are really looking to support complex `input` object, not just single-level attributes.

Sometimes we really would like to call our tag function with complex `input` object. In JavaScript this is really simple and straightforward:

```js
appTabs({
    orientation: "vertical",
    tabs : [
        { label: "Tab 1", renderBody: function() { return "Content for Tab 1" } },
        { label: "Tab 2", renderBody: function() { return "Content for Tab 2" } }
    ],
    renderBody: function() { ... }
};
```
Today we cannot easily do the same declaratively. We can pass `orientation` attribute, but we cannot pass `tabs[]` array. Proposal #61 tries to solve this, but conceptually it is a bit complex, because it requires to introduce another tag that is defined separately from the `attributes` attribute in `marko-taglib.json`, while still attaching to the `input` object with the help of `target-property`. I see mismatch here: from one side we have independent child tag, from other side we are trying to embed it to our parent's `input` object.

What if the problem can be defined as the following: *how can we make declarative "call" of tag function that accepts complex `input` objects?* This definition of the problem is differ from the current problem: *how can we simplify parent/child relationships?*

### Proposal for `marko-taglib.json` syntax

If our tag function can accept complex `input` objects then shape of such object should be defined inside `attributes`, where we currently have support for only first-level attributes. Here is a possible definition of `app-tabs` taglib:

```js
{
    "attributes": {
        "orientation": "string",
        "tabs": {
            "type": "object[]",
            "implicit": true,    // only one attribute can be implicit (more about this below)
            "attributes": {
                "label": "string"
            }
    }
}
```

### Nested tags vs. nested attributes

Nested tag is a complete Marko tag which is nested to another tag and can be reused. Nested attributes can look like ordinary Marko tags, but they cannot be reused outside of the root tag.

In the following example, `<app-panel />` is a nested tag, while `<app-tab />` is a nested attribute of `<app-tabs />`:

```html
<app-tabs orientation="vertical">
    <app-tab label="Tab 1">
        <app-panel title="Title" />
    </app-tab>
    <app-tab label="Tab 2">
        Content for Tab 2
    </app-tab>
</app-tabs>
```

We cannot reuse `<app-tab />` outside of the root `<app-tabs />`. That is why this is a nested attribute. But we can reuse `<app-panel />`, because this is a nested tag.

Important part of this proposal is a proposal to treat nested tags differently from the nested attributes.

### Proposal for the syntax of nested attributes

There are several possible ways to express nested attributes. First possible way is to use `tag-name.property` notation:

```html
<app-tabs orientation="vertical">
    <app-tabs.tab label="Tab 1">
        <app-panel title="Title" />
    </app-tabs.tab>
    <app-tabs.tab label="Tab 2">
        Content for Tab 2
    </app-tabs.tab>
</app-tabs>
```

The following `input` object will be created (renderBody etc. are omitted):

```js
{
    "orientation": "vertical",
    "tabs": [
        { "label": "Tab 1" },
        { "label": "Tab 2" },
    ]
```

I saw such notation in the [XAML](https://msdn.microsoft.com/en-us/library/ms788723%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) language:

```xml
<Button Text="Save">
  <Button.ContextMenu>   <!-- nested attribute -->
    <ContextMenu>     <!-- nested tag -->
      <MenuItem Header="1">First item</MenuItem>
      <MenuItem Header="2">Second item</MenuItem>
    </ContextMenu>
  </Button.ContextMenu>
  Right-click me!
</Button>
```

Second possible way is to use some special `param` tag, like in [Google Closure Templates](https://developers.google.com/closure/templates/docs/commands#param):

```txt
{template <template_name>}
  {@param <param_name>: <param_type>}
  {@param? <optional_param_name>: <param_type>}
  ...
{/template}
```

In case of Marko it can be `<@param attribute1="value" attribute2="value" />`, although I also don't like special symbols (maybe simple `<param ... />` is enough):

```html
<app-tabs orientation="vertical">
    <@tab label="Tab 1">
        <app-panel title="Title" />
    </@tab>
    <@tab label="Tab 2">
        Content for Tab 2
    </@tab>
</app-tabs>
```

Marko already has special syntax for string interpolation: `${value}`, `$!{value}` and `${value}`. Maybe it still worth to add another special syntax for nested attributes: `<@name />` or any other.

I'm not voting for any particular syntax, my idea is to evaluate problem that we are trying to solve from different angle (from declarative definition of complex `input` objects). I'm sure that together we can find a better syntax.

#### 

In my comment to #61 I asked about support for more than one level of nested tags with the following use case:

```html
<sidebar-navigation>
    <sidebar-navigation-section title="Software">
        <sidebar-navigation-item href="/linux" title="linux"/>
        <sidebar-navigation-item href="/windows" title="Windows"/>
    </sidebar-navigation-section>
    <sidebar-navigation-section title="Devices">
        <sidebar-navigation-item href="/ipad" title="iPad"/>
        <sidebar-navigation-item href="/xbox" title="Xbox"/>
    </sidebar-navigation-section>
</sidebar-navigation>
```

When looking on this template, can you answer on what tags are "nested tags" and what are just "nested attributes"? It is hard to answer on this question without reading `marko-taglib.json`. If we can find a way to differentiate tags from attributes, it can be expressed in the following way (using some of the proposed syntax):

```html
<sidebar-navigation>
    <@section title="Software">
        <@item href="/linux" title="linux"/>
        <@item href="/windows" title="Windows"/>
    </@section>
    <@section title="Devices">
        <@item href="/ipad" title="iPad"/>
        <@item href="/xbox" title="Xbox"/>
    </@section>
</sidebar-navigation>
```

Definition of this tag in `marko-taglib.json`:

```js
{
    "attributes": {
        "orientation": "string",
        "sections": {
            "type": "object[]",
            "implicit": true,    // only one attribute on the same level can be implicit 
            "attributes": {
                "title": "string",
                "items": {
                    "type": "object[]",
                    "implicit": true,   // only one attribute on the same level can be implicit 
                    "attributes": {
                        "title": "string",
                        "href": "string"
                    }
                }
            }
        }
    }
}
```

`implicit` flag means that we can assign value to this property using shorter notation. Instead of this (technically valid):

```html
<sidebar-navigation>
    <@sections>
        <@section title="Software" />
    </@sections>
<sidebar-navigation>
```
 We can write it in the shorter form:

```html
<sidebar-navigation>
    <@section title="Software" />
<sidebar-navigation>
```

In XAML this flag is named [`ContentProperty`](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.markup.contentpropertyattribute.Aspx).

#### Conclusion

This is just a proposal. You probably see much more corner stones than I am. 

Thank you!

**Comment by philidem** [comment]
@schetnikovich Excellent proposal! You did a great job capturing the disconnect between nested tags and how their values are actually used by the parent widget. I think you're exactly right that they're more like attributes since the complex values for the nested tag get stored the same way as attributes (based on the proposals we have so far).

We need to make sure that this remains valid HTML. I don't think the HTML parser will allow `.` and `@` in the tag names (haven't verified this yet), and for that reason we could try to use XML namespaces instead of a new syntax. For example:
```xml
<app-tabs>
    <app-tabs:tab label="Tab 1">
        Content for Tab 1
    </app-tabs:tab>
    <app-tabs:tab label="Tab 2">
        Content for Tab 1
    </app-tabs:tab>
</app-tabs>
```
At one name every tag could be put into a namespace but then we decided to require that all tags be named uniquely. For example, instead of creating a namespace with name "app" and using `<app:tabs>` we moved toward `<app-tabs>`. I think we need to completely remove that namespace code.

If the HTML parser will allow `@` and `.` in an HTML tag then it might be worth considering that notation as well. We could fork the HTML parser that we are using. There is a precedence of using `@` to indicate attributes. If we could interpret `@` to mean "this tag belongs to the closest parent tag" then we could automatically bind nested tags as attributes to parent tag. If the nested tag is not the direct descending then maybe we could support a qualifier. Also, if we go this route then we'll need to enhance the Marko syntax highlighter for Atom (and possibly create one for other editors such as Sublime Text).

For example, simple case that doesn't require qualifiers:
```xml
<app-tabs>
    <@tab>
        <@label>Tab 1</@label>
        Content for Tab 1
    </@tab>
    <@tab>
        <@label>Tab 2</@label>
        Content for Tab 1
    </@tab>
</app-tabs>
```

For example, less simple case that does require qualifiers:
```xml
<app-tabs>
    <if test="data.readOnly">
        <@app-tabs.tab>
            <@label>Tab 1</@label>
            Content for Tab 1
        </@app-tabs.tab>
    </if>
    <@tab>
        <@label>Tab 2</@label>
        Content for Tab 1
    </@tab>
</app-tabs>
```

Also, I wonder if we can support nested tags within nested tags. For example, using the namespace notation:
```xml
<app-tabs>
    <app-tabs:tab>
        <app-tabs:tab:label>Tab 1</app-tabs:tab:label>
        Content for Tab 1
    </app-tabs:tab>
    <app-tabs:tab>
        <app-tabs:tab:label>Tab 2</app-tabs:tab:label>
        Content for Tab 1
    </app-tabs:tab>
</app-tabs>
```

If we hit limitations with the HTML parser that we're using then maybe we should consider writing our own because that would provide some other niceties.

I've been interested in doing this:
```xml
<app-button size={data.buttonSize}></app-button>
```

I'm definitely going to think about this some more!

**Comment by DanCech** [comment]
It might be possible sidestep the tag-name issues and instead define a new marko-tag like `<attribute name="X">value</attribute>`, which would set an attribute on the parent tag.  In this use-case the markup for the tabs might look something like:
```
<app-tabs>
    <attribute name="tab">
        <attribute name="label">Tab 1</attribute>
        Content for Tab 1
    </attribute>
    <attribute name="tab">
        <attribute name="label">Tab 2</attribute>
        Content for Tab 1
    </attribute>
</app-tabs>
```
This scheme could potentially be used for defining attributes on regular html tags as well as on our custom taglib tags too, though I have no idea how much complexity that would add to the parser.

**Comment by patrick-steele-idem** [comment]
Thanks for the proposal, @DanCech. I like the idea of having a shorthand for nested tags. 

Technically, HTML 5 does allow any character for the tag name but the first character must match`[a-zA-Z]`. This only made clear if you look at the tokenization spec:
http://www.w3.org/TR/2011/WD-html5-20110113/tokenization.html#tag-open-state
http://www.w3.org/TR/2011/WD-html5-20110113/tokenization.html#tag-name-state

Therefore, unless we fork the parser that we are using and are willing to break syntax highlight in all HTML editors then we should conform to the HTML spec.

I don't consider `<attribute>` as a replacement for repeatable nested tags for two reasons:

- Marko already supports nested `<attr>` tags that can be used to add HTML attributes to the parent element (not documented, but [here is a relevant test](https://github.com/raptorjs/marko/blob/9e3bbfe882af26e9eda63a5e86e69651a3a3dfcb/test/fixtures/templates/nested-attrs/template.marko#L4-L5))
- Real attributes cannot be repeated

Just to be clear, the following is already supported:

```html
<app-tabs>
    <app-tab>
        <attr name="label">Tab 1</attr>
        Content for Tab 1
    </app-tab>
    <app-tab>
        <attr name="label">Tab 2</attr>
        Content for Tab 2
    </app-tab>
</app-tabs>
```

Regarding nested tags, I think we should consider the following options:

## Option 1: Use a colon to namespace nested tags:

```html
<app-tabs>
    <app-tabs:tab label="Tab 1">
        Content for Tab 1
    </app-tabs:tab>
    <app-tabs:tab label="Tab 2">
        Content for Tab 2
    </app-tabs:tab>
</app-tabs>
```

Pros:

- The colon character is already associated with namespacing and a nested tag is namespaced within a parent element.
- In the future, we may want to support a short-hand by dropping the parent namespace part (e.g., `<app-tabs:tab>` → `<:tab>`
- Most HTML editors should not have a problem with a colon character in a tag name

Cons:

- Looks like XML namespaces (can be a turn off to some people)
- Colon character is harder to type (requires the `SHIFT` key)
- More typing

## Option 2: use a period to namespace nested tags:

```html
<app-tabs>
    <app-tabs.tab label="Tab 1">
        Content for Tab 1
    </app-tabs.tab>
    <app-tabs.tab label="Tab 2">
        Content for Tab 2
    </app-tabs.tab>
</app-tabs>
```

Pros

- Same as Option 1 _plus_ the period character is easier to type (no `SHIFT` key)

Cons

- Not sure how most HTML editors, parsers and linters will feel about a `period` character in the tag name
- More typing

## Option 3: Use a dash separator for the nested tag name:

```html
<app-tabs>
    <app-tabs-tab label="Tab 1">
        Content for Tab 1
    </app-tabs-tab>
    <app-tabs-tab label="Tab 2">
        Content for Tab 2
    </app-tabs-tab>
</app-tabs>
```

## Option 4: Use no explicit namespacing and just rely on a unique tag name:

```html
<app-tabs>
    <app-tab label="Tab 1">
        Content for Tab 1
    </app-tab>
    <app-tab label="Tab 2">
        Content for Tab 2
    </app-tab>
</app-tabs>
```

-----------

Thoughts on which option is best? I'm leaning towards Option 2 (using a period as a separator), but I think we need to see how various tools feel about a period in the tag name.

**Comment by DanCech** [comment]
Interesting, I didn't know about <attr>.  Is that something that's intended to be documented and officially supported?

I think the colon approach will result confusion since the `app-tabs` "namespace" wouldn't actually be declared, and could cause problems for people trying to use marko to generate xml.

The . or - separated syntax seems cleanest, if a little repetitive.  The ability to just declare arbitrary subtag names in the taglib definition could result in some interesting use-cases and has the potential to make the template markup more "semantic", which is a pretty big pro in my book.

**Comment by patrick-steele-idem** [comment]
@schetnikovich I think I missed the main purpose of your proposal. Your goal was to normalize attributes and nested tags and I think that is a good idea. What do you think of the following variation?:

`app-tabs/marko-taglib.json`:

```json
{
    "attributes": {
        "orientation": "string",
        "tabs": {
            "type": "object[]",
            "nested-tag": {
                "name": "tab",
                "attributes": {
                    "label": "string",
                    "body": "string"
                }
            }
        }
    }
}
```

You would then have two options for passing in the array of tabs:

## Using the tabs attribute:

```html
<app-tabs tabs="[ { label: 'Foo', body: 'Content for Foo' }, { label: 'Bar', body: 'Content for Bar' }, ... ]"/>
```

## Using the nested tab tag:

```html
<app-tabs>
    <app-tabs.tab label="Tab 1">
        Content for Tab 1
    </app-tabs.tab>
    <app-tabs.tab label="Tab 2">
        Content for Tab 2
    </app-tabs.tab>
</app-tabs>
```

--------

Also, there is no right answer on whether or an attribute is more appropriate then a nested tag for passing input to a custom tag. Key differences between attributes and nested tags is that attributes cannot be repeated and attributes cannot contain complex markup. Nested tags do not have those limitations. I believe we need to support both attributes and nested tags.

**Comment by patrick-steele-idem** [comment]
Completely agree with your comments @DanCech. Even if it is more typing, I think it is better to have some concept of explicit namespacing and I think it is better to avoid the colon character. I could go either way on `<app-tabs.tab>` vs `<app-tabs-tab>`, but I am leaning towards `<app-tabs.tab>` because the syntax makes it clear that it is a nested tag (i.e. not a top-level tag) and that will hint to the user where the nested tag is defined. 

As for `<attr>`, yes that feature is officially supported. It is an oversight that the documentation does not mention `<attr>` tag. Pull requests welcome :)

**Comment by philidem** [comment]
I'm in favor of supporting the dot-notation for using nested tags in your HTML. A short-hand of only using something like `<.tab>` would be great too if we can tweak the HTML parser.

I have a new proposal for `marko-tag.json` that should reduce the characters via a short-hand notation.

I propose that we use "@" as a property prefix to identify attributes instead of having to nest them under a `attributes` property.

For example:
```json
{    
    "@orientation": "string",
    "@tabs <tab>[]": {
        "@label": "string",
        "@body": "string"
    }
}
```

The `@tabs <tab>[]` portion of the example above would be interpreted as:
"tabs can also be provided via one or more nested tab tags"

Thoughts?

**Comment by patrick-steele-idem** [comment]
Great suggestion @philidem! I really like the much flatter and more concise structure and I think it allows us to capture all of the same information. I do have a few minor concerns:

1. Symbols have meaning (slightly higher learning curve)
2. The fact that the `tabs` attribute is an expression type would be implicit instead of explicit

We can mitigate the first concern by first introducing developers to the long-hand form (that we would always need to support) and then provide the equivalent short-hand syntax.

:+1: for the following:

```json
{    
    "@orientation": "string",
    "@tabs <tab>[]": {
        "@label": "string",
        "@body": "string"
    }
}
```

**Comment by schetnikovich** [comment]
> I'm in favor of supporting the dot-notation for using nested tags in your HTML. 
> A short-hand of only using something like <.tab> would be great too if we can 
> tweak the HTML parser.

Because you are already planning to use `@` symbol for attributes, maybe it makes sense to introduce `@<nested-tag />` notation, instead of `<.nested-tag />` and `<@nested-tag />`:

```html
<app-tabs>
    @<tab label="Tab 1">
        Content for Tab 1
    </tab>
    @<tab label="Tab 2">
        Content for Tab 2
    </tab>
</app-tabs>
```

It seems that in this case we shouldn't worry about HTML parsers and all editors will work fine with this syntax.

As a side note, we also can continue to use `$` symbol for this and do not introduce new symbol:

```html
<app-tabs>
    $<tab label="Tab 1">
        Content for Tab 1
    </tab>
    $<tab label="Tab 2">
        Content for Tab 2
    </tab>
</app-tabs>
```

Mnemonic is the following: when `$` is in front of open curly bracket (`{`), you are going to evaluate JavaScript expression. When `$` is in front of open tag (`<tag>`), you are going to decoratively define  sub-property.

**Comment by patrick-steele-idem** [comment]
Just an update. Based on the feedback shared in this Github issue (and the related Github issue of #61) we have made changes to support the following:

- Better support for tags with a parent/child relationship
- Shorthand syntax for defining tags and attributes

The Pull Request is still being reviewed, but you can find the details in the CHANGELOG for the upcoming `marko@2.4.0`: https://github.com/patrick-steele-idem/marko/blob/parent-child/CHANGELOG.md#240

Here's the Pull Request with the changes: #68 


Feedback on this Pull Request is greatly appreciated. Thanks!

**Comment by patrick-steele-idem** [comment]
Support for parent/child relationships has been completed. Closing issue.
