### ISSUE TITLE
Layout-put not working anymore

### ISSUE THREAD

**Issue by viviangledhill** [raptorjs/marko#72]
It seems like the layout-put tag is not working as expected anymore. The test confirms this:

```
4) render layout-use:
     Error: Unexpected output for "/marko/test/fixtures/templates/layout-use/template.marko":
EXPECTED (/marko/test/fixtures/templates/layout-use/expected.html):
---------
<div>BODY CONTENT</div>FOOTER CONTENT<h1>HEADER CONTENT</h1><div>BODY CONTENT</div>FOOTER CONTENT<h1>VALUE HEADER</h1><div>BODY CONTENT</div>FOOTER CONTENT<h1>DEFAULT TITLE</h1><div>BODY CONTENT</div>FOOTER CONTENT
---------
ACTUAL (/marko/test/fixtures/templates/layout-use/actual.html):
---------
<div></div><h1>DEFAULT TITLE</h1><div></div><h1>DEFAULT TITLE</h1><div></div><h1>DEFAULT TITLE</h1><div></div>
---------
```

Instead of using the content from layout-put it falls back to the default if available.

Any idea what's wrong here?

**Comment by patrick-steele-idem** [comment]
I'm not seeing any failing tests and our CI never reported any failing tests. I will take a look and see if I can reproduce and report back soon.

Thanks for reporting the problem.

**Comment by patrick-steele-idem** [comment]
@viviangledhill I just did a refresh `npm install` with the latest code of `marko@2.4.0` (`master` branch) and I am still not able to reproduce the problem. Which version of marko are you testing with?

**Comment by patrick-steele-idem** [comment]
I also tested with the latest code on the `v1.6` branch and am not able to reproduce.

**Comment by patrick-steele-idem** [comment]
Also, one other thought: if you have `marko-layout` or `marko-async` installed as dependencies in your project then you should remove those dependencies. Both `marko-layout` and `marko-async` are core dependencies of `marko` and are already included. Having multiple versions of those modules might be causing problems in your app.

**Comment by viviangledhill** [comment]
That is strange. If I checkout the latest version with a blank npm install ... it's still failing. 

I'm using node 0.10.36.

Any idea how I could triage this issue?

**Comment by viviangledhill** [comment]
Did the same on a different machine. Everything went fine without issues. Most likely it's just a problem with my machine. 

Let me know if you have any idea how I could isolate this issue.

Thanks
-Vivian

**Comment by patrick-steele-idem** [comment]
@viviangledhill Did you try deleting your `node_modules` directory?

**Comment by viviangledhill** [comment]
Yes, did that without success.

Anyhow, found the issue.

There was a node_modules directory in a parent directory by accident. So for some reason it interfered with that and caused these errors.

Thanks for your quick help!
-Vivian

**Comment by patrick-steele-idem** [comment]
Ok. Interesting. I'll look into making a change to prevent the core taglibs from loading multiple times even though it is an edge case. Thanks for the update and I'm glad you got everything working.
