### ISSUE TITLE
Adding query params to url when rendering template

### ISSUE THREAD

**Issue by patbegg** [raptorjs/marko#81]
Hi,
How can query params be added to a url when rendering a template `template.render({}, res);` so they can be accessed from the url e.g. http://domain.com/book?id=123 ?

**Comment by DanCech** [comment]
Assuming you have a request object like Express provides:
```
template.render({id: req.query.id}, res);
```
Then in the template:
```
<a href="http://domain.com/book?id=${data.id}">click</a>
```

**Comment by patbegg** [comment]
Thanks. I want to be able to append it to the url so I can then parse the URL for the page to access all the params via JS. I understand I can render a `<script>` tag in the template with the values but it would be a better solution to parse the URL in this case.

Is this possible do you know?

**Comment by DanCech** [comment]
I'm not sure that I follow what you're asking to be honest.  If you just want to access the query params from js in the browser you can do that without marko involvement at all by parsing `window.location.search` with client-side js. If you want to use marko to pass any requested params back to the template you could stick the entire `req.query` object into `data` like:
```
template.render({query: req.query}, res);
```
Then:
```
<script>
  var query = $!{JSON.stringify(data.query)};
</script>
```

**Comment by patbegg** [comment]
I've not explained this great. I'll have another go. 
(using Express + Marko)
Say I have a form submitted to '/book/:id' route, this is handled by a controller which saves the book to the DB. Once the book is saved I render a template '/book/complete'. But instead of the url being '/book/complete' I want it to be '/book/complete?id=123' (123 being the last ID added to the DB).
My problem is rendering the query string onto the URL on page load.

Your second solution makes sense but having script tags could get unwieldy across pages.

Does that explain it any better?
Thanks for persevering.

**Comment by DanCech** [comment]
Honestly this doesn't sound like a marko issue at all, the URL in the browser isn't related to the name of the template.  If you want to have the browser show that URL you'll need to add a GET route for it and at the end of your POST handler use a redirect to make the browser load the desired URL.
```
return res.redirect('/book/complete?id=' + new_id);
```

**Comment by patrick-steele-idem** [comment]
If I am following correctly then I would agree with @DanCech that you are looking to do a server-side redirect. Please let us know if that is the answer you are looking for or if there is a question more specific to Marko.

**Comment by patbegg** [comment]
Couldn't see the wood for the trees! Thanks @DanCech.
