### ISSUE TITLE
Support for JavaScript execution within element.

### ISSUE THREAD

**Issue by SunnyGurnani** [raptorjs/marko#92]
I was working on creating reusable helper utility which will add _sp, class and id to any element when passing a common data model. After alot of try and error with variables, functions and ${} and without ${} I finally concluded that it may not be supported.

Support for calling a Helper Utility to render anything within the HTML element is desired.

Currently Marko supports calling JavaScript expression on right hand side after = sign (as below)

However following is not supported. hello

I have created a sample to explain the same.
https://github.corp.ebay.com/sugurnani/marko-dynamic-attributes/tree/master

**Comment by patrick-steele-idem** [comment]
For the benefit of those outside eBay, here's the template that you shared:

```xml
<div ${helper.renderAttributes()} >
    Please inspect my container element and you will find dynamic content is not evaluated
</div>
```

The above is not valid HTML and will not be parseable. However, the equivalent alternative is to take advantage of the custom [attrs](https://github.com/raptorjs/marko#attrs) attribute as shown below:

```xml
<div attrs="helper.getTrackingAttributes()">...</div>
```

Where the `helper.getTrackingAttributes` is implemented as shown below:

```javascript
function getTrackingAttributes() {
    return {
        "attr1": "attr1Value",
        "attr2": "attr2Value"
    }
}
```

Alternatively, you could use a custom compile-time transform to add the attributes to allow for something similar to the following:

```xml
<div tracking-attrs/>
```

Let me know if this answers your question or if you would like more help with a custom compile-time transform.

**Comment by SunnyGurnani** [comment]
Thank you @patrick-steele-idem 

I was saw the documentation for defining custom tags but was unable to find info about creating custom attributes. Can you please point me to that doc?

**Comment by patrick-steele-idem** [comment]
Hi @SunnyGurnani, I was hoping to put together a sample app to demonstrate custom compile-time transforms to process custom attributes, but I have been pretty swamped. In the meantime, it might be helpful to understand how marko-widgets utilizes compile-time transforms.

Here is the implementation for the marko-widgets compile-time transform:
https://github.com/raptorjs/marko-widgets/blob/master/taglib/widgets-transformer.js#L21

Here is the taglib that registers the transform:
https://github.com/raptorjs/marko-widgets/blob/master/marko-taglib.json#L70

I still hope to improve the docs for this advanced feature, but hopefully this helps in the meantime. Thanks for your patience.

**Comment by patrick-steele-idem** [comment]
Closing this issue. I have opened another issue to improve the docs for compile-time transforms to better explain how custom tags and custom attributes can be processed at compile-time: https://github.com/raptorjs/marko/issues/100
