### ISSUE TITLE
Support for JavaScript value in Custom Attributes

### ISSUE THREAD

**Issue by SunnyGurnani** [raptorjs/marko#93]
Custom Attributes is a great functionality. But current implementation does NOT support attribute value to come from a object.

Following statement is currently supported. but what if class name is coming dynamically from the JavaScript object.
<div class="{?data.active;tab-active}"></div>

Support for following is needed
<div class="{?data.active;data.model.class}"></div>

Also there is inconsistency across marko for defining JavaScript expression. Some places its using ${}, some places it dosent needs ${} and here its using {?condition;value} (WITHOUT $ sign)

**Comment by patrick-steele-idem** [comment]
You mentioned two separate issues:

> what if class name is coming dynamically from the JavaScript object.

For that you will want to use the custom `attrs` attribute which allows attributes to come from a JavaScript object: https://github.com/raptorjs/marko#attrs

> Also there is inconsistency across marko for defining JavaScript expression. Some places its using ${}, some places it dosent needs ${} and here its using {?condition;value} (WITHOUT $ sign)

That is a known issue that would be solved with the following proposal: https://github.com/raptorjs/marko/issues/90 (Proposal: Replace HTML parser with a new parser that recognizes attribute types)

Please let me know if that does or does not address your concern so that I can close this issue. Thanks.

**Comment by SunnyGurnani** [comment]
Thank you Patrick I didnt knew about attrs attribute, I have to finish up reading entire doc :)

On the second note It would be helpful if we can unify conditional statements as well for example below dosent with with <assign> but works with <html class={?}>
<assign var="viewDetailsClass" value="{?data.listingModel.bin.binAction;btn;btn btn--primary}"/>

May be using just using javascript inline if statement everywhere can solve the problem.

**Comment by patrick-steele-idem** [comment]
Hi @SunnyGurnani, If an attribute type is declared as `expression` (such as `value` attribute for the `<assign>` tag) then the attribute value is assumed to be a valid JavaScript expression. Therefore you would need to have the value be valid JavaScript such as the following:

```javascript
<assign var="viewDetailsClass" value="data.listingModel.bin.binAction ? 'btn' : 'btn btn--primary'"/>
```

Longer term, we want to have everything be JavaScript. Again, this would be solved by the following proposal: https://github.com/raptorjs/marko/issues/90 :)
