### ISSUE TITLE
Problem passing data to nested partials (templates)

### ISSUE THREAD

**Issue by kristianmandrup** [raptorjs/marko#98]
We initially tried to use 

`<include name="xyz.marko" data="${data}"/>`

but this is (obviously!) a terrible idea whioch doesn't work. What is the recommended pattern, besides copying down each specific value which the partial is depending on, which can quickly make for tight coupling in the hierarchy!!

`<include name="xyz.marko" page="${data.page}" providers="${data.providers}"/>`

**Comment by jcc2303** [comment]
We have this problem 

views/layouts/default-layout.marko:
 ....  <include template="./../partials/header/header.marko" menu_items="$data.globals"/>

views/partials/header/header.marko:
<p>${data.menu_items}</p>

and is empty data

**Comment by patrick-steele-idem** [comment]
Hi @kristianmandrup,  I updated the docs to mention the `template-data` attribute that is supported on the `<include>` tag. For your example, you would want to do the following:

```xml
<include name="xyz.marko" template-data="${data}"/>
```

Here's a link to the relevant docs that now mentions the `template-data` attribute:
https://github.com/raptorjs/marko#includes

Please let me know if that doesn't solve your problem.

Thanks.

**Comment by patrick-steele-idem** [comment]
Hey @jcc2303, can you please provide more details on your problem? I believe it is best to open a separate Github issue because your code seems unrelated to what @kristianmandrup described. Please clarify. Thanks.
